driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    apt:
      compiletime: true
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  attributes:
    apt:
      compiletime: true
- name: centos-6.7

suites:
  - name: default # nginx, postgresql
    run_list:
      - recipe[test-helper]
      - recipe[crowd]

  - name: apache2
    run_list:
      - recipe[test-helper]
      - recipe[crowd]
    attributes:
      crowd:
        proxy:
          type: apache2
